### ISSUE TITLE
 serverless module install fails

### ISSUE THREAD

**Issue by kennethlynne** [serverless/serverless-slack#3]
``` bash
 serverless module install https://github.com/serverless/serverless-slack
/.nvm/versions/node/v5.3.0/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:49
        fn = function () { throw arg; };
                           ^

ServerlessError: Command not found.  Enter "serverless help" to see all available commands.
    at new ServerlessError (.nvm/versions/node/v5.3.0/lib/node_modules/serverless/lib/Error.js:17:11)
    at Serverless.command (.nvm/versions/node/v5.3.0/lib/node_modules/serverless/lib/Serverless.js:355:31)
    at .nvm/versions/node/v5.3.0/lib/node_modules/serverless/bin/serverless:19:16
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at Object.<anonymous> (.nvm/versions/node/v5.3.0/lib/node_modules/serverless/bin/serverless:18:4)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
    at startup (node.js:141:18)
    at node.js:980:3

```

**Comment by franz-josef-kaiser** [comment]
@kennethlynne When you enter `serverless` (or `sls`), then you will see that the `module` "action" is not available anymore. I am currently as well searching what the replacement is.

**Comment by flashsnake-so** [comment]
:(

**Comment by cfehring** [comment]
Austen's Jan 18 note at https://gitter.im/serverless/serverless states:
"Temporary Removal Of Module Install: We've temporarily removed the module install command so that it will work with our new shareable module design. This will be back shortly."
